### ISSUE TITLE
String literals crash the compiler

### ISSUE THREAD

**Issue by qexat** [qexat/pyvism#11]
Input:

```
&0 ^l "Hello!\n" ^n
```

Output:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/qexat/Repositories/vism/src/pyvism/__main__.py", line 4, in <module>
    raise SystemExit(main())
                     ^^^^^^
  File "/home/qexat/Repositories/vism/src/pyvism/cli.py", line 43, in main
    return main_debug()
           ^^^^^^^^^^^^
  File "/home/qexat/Repositories/vism/src/pyvism/cli.py", line 28, in main_debug
    match (result := compiler.compile()):
                     ^^^^^^^^^^^^^^^^^^
  File "/home/qexat/Repositories/vism/src/pyvism/compiler.py", line 482, in compile
    self.process_buffered()
  File "/home/qexat/Repositories/vism/src/pyvism/compiler.py", line 332, in process_buffered
    value = evaluate(str_value, self.assign_type)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qexat/Repositories/vism/src/pyvism/compiler.py", line 66, in evaluate
    return Ok(literal_eval(unparsed_value))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ast.py", line 64, in literal_eval
    node_or_string = parse(node_or_string.lstrip(" \t"), mode='eval')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<unknown>", line 1
    "Hello!
    ^
SyntaxError: unterminated string literal (detected at line 1)
```

The `evaluate` function will crash on strings because it tries to parse the incorrect version of the unparsed value.

**Comment by qexat** [comment]
This should be easy to fix.
